const fs=require('fs'),vm=require('vm');
class CL{constructor(){this.s=new Set()}add(x){this.s.add(x)}remove(x){this.s.delete(x)}contains(x){return this.s.has(x)}toggle(x,f){if(f===undefined)f=!this.s.has(x);f?this.s.add(x):this.s.delete(x)}}
class E{constructor(tag='div'){this.tagName=tag;this.children=[];this.listeners={};this.dataset={};this.classList=new CL();this.textContent='';this.value='';this.disabled=false;this.files=[]}addEventListener(n,f){this.listeners[n]=f}append(...x){this.children.push(...x)}removeChild(x){this.children.splice(this.children.indexOf(x),1)}get firstChild(){return this.children[0]||null}closest(){return null}focus(){}scrollIntoView(){this.scrolled=true}setAttribute(n,v){this[n]=v}querySelector(){return null}click(){if(this._click)this._click()}}
const selectors=['#messages','#composer','#message','#send','#attachments','#attachment-tray','#status','#auth','#auth-form','#token','#connect','#auth-error','#developer-content','#developer-build','#detail-panel','#detail-content','#sound-settings','#presence-settings','#library-content','#library-search-form','#library-query','#history-content','#history-search-form','#history-query','#history-domain','#phoenix-name','.app-nav','#developer-sections','#detail-close','#chat-view','#developer-view','#settings-view','#library-view','#history-view'];
const n=Object.fromEntries(selectors.map(x=>[x,new E()]));n['#developer-build'].textContent='Build: test-build';
const attentionId=process.env.FAWKES_ATTENTION_ID||'attention-test';
const devButton=new E('button');devButton.dataset.view='developer';devButton._click=()=>n['.app-nav'].listeners.click({target:{closest:()=>devButton}});
const attentionTab=new E('button');attentionTab.dataset.section='attention';
global.window={location:{origin:'http://localhost:8787',search:`?view=developer&section=attention&attention=${attentionId}`},localStorage:{getItem:()=> 'old-credential-must-not-be-used',setItem(){}},setTimeout,clearTimeout,dispatchEvent(){}};
global.CustomEvent=class{};global.Event=class{};
global.document={querySelector(s){if(s==='.app-nav [data-view="developer"]')return devButton;return n[s]||null},querySelectorAll(s){if(s==='#developer-sections [data-section]')return [attentionTab];if(s==='.app-nav [data-view]')return [devButton];return []},getElementById(id){return descendants(n['#developer-content']).find(x=>x.id===id)||null},createElement:t=>new E(t),createElementNS:(_,t)=>new E(t),addEventListener(){}};
function descendants(x){return x.children.reduce((a,c)=>a.concat(c,descendants(c)),[])}
const scenario=process.env.FAWKES_ATTENTION_SCENARIO||'valid';let sessionEstablished=!['auth-login','auth'].includes(scenario);const submissions=[];
const pending={attention_id:attentionId,campaign_id:`campaign-${attentionId}`,invocation_id:`invocation-${attentionId}`,state:scenario==='resolved'?'deny':'needs_tanner',blocked_action:'run harmless check',why_required:process.env.FAWKES_EXPECTED_CHOICE==='deny'?'Test B — DENY — Expected qualification choice: Deny':'Test A — APPROVE ONCE',requested_authority:'one harmless action',resources:['probe'],reversible:true,protocol_binding:{method:'item/commandExecution/requestApproval',item_id:`item-${attentionId}`,approved_action_sha256:`digest-${attentionId}`},protocol_binding_sha256:`binding-${attentionId}`};
global.fetch=async (path,options={})=>{let status=200,data={};path=String(path);if(path==='/api/session'){sessionEstablished=JSON.parse(options.body||'{}').credential==='app-specific-credential';status=sessionEstablished?204:401;data=sessionEstablished?{}:{error:{message:'That Fawkes app credential was not accepted.'}}}else if((scenario==='auth'||scenario==='auth-login')&&!sessionEstablished&&path!=='/api/status'){status=401;data={error:{message:'Access token required.'}}}else if(path.includes('/decision')){const body=JSON.parse(options.body);submissions.push({path,body});data={attention:{...pending,state:body.choice},decision:{choice:body.choice,lifecycle_state:'completed'}}}else if(path==='/api/chat')data={phoenix:{name:'Fawkes'},conversation:{conversation_id:'c'},messages:[]};else if(path==='/api/status')data={build:{release_id:'test-build'}};else if(path==='/api/development/dashboard')data={};else if(path==='/api/development/codex-campaigns')data={campaigns:[]};else if(path==='/api/development/attention')data={attention:[pending]};else if(path.includes(`/api/development/attention/${attentionId}`)&&scenario==='unknown'){status=404;data={error:{message:'That Tanner attention request does not exist in this Fawkes build.'}}}else if(path.includes(`/api/development/attention/${attentionId}`))data={attention:pending,decision:scenario==='resolved'?{lifecycle_state:'completed',consumed:true,creates_continuing_authority:false}:null};else{status=404;data={error:{message:'Not found.'}}}return{status,ok:status<400,json:async()=>data}};
vm.runInThisContext(fs.readFileSync('src/app/static/app.js','utf8'),{filename:'app.js'});
if(scenario==='auth-login')setTimeout(async()=>{n['#token'].value='app-specific-credential';await n['#auth-form'].listeners.submit({preventDefault(){}})},5);
setTimeout(async()=>{let all=descendants(n['#developer-content']);const text=all.map(x=>x.textContent).join('\n');const effective=scenario==='auth-login'?'valid':scenario;let wanted=effective==='valid'?['Tanner: Fawkes is paused and needs your decision','What Fawkes wants to do','Approve Once','Deny','Cancel']:effective==='resolved'?['already resolved','Decision outcome','No continuing authority']:effective==='unknown'?['Attention request unavailable','unknown or no longer retained']:['Attention request unavailable','Authenticate to inspect'];for(const value of wanted)if(!text.includes(value))throw Error('missing '+value+' in '+text);if(effective==='valid'&&!all.some(x=>x.tagName==='details'))throw Error('technical details are not collapsed');if(!attentionTab.classList.contains('active'))throw Error('Attention tab not selected');if(scenario==='auth'&&n['#auth'].classList.contains('hidden'))throw Error('authentication boundary not shown');if(effective==='valid'&&!all.some(x=>x.id===`attention-${attentionId}`))throw Error('wrong exact attention card');const choice=process.env.FAWKES_EXPECTED_CHOICE;if(choice&&effective==='valid'){const needle=choice==='deny'?'Deny — Test B':'Approve Once — Test A';const button=all.find(x=>x.tagName==='button'&&x.textContent===needle);if(!button)throw Error('missing exact decision button '+needle);await button.listeners.click();const sent=submissions[0];if(!sent||sent.body.choice!==choice||sent.body.identity.attention_id!==attentionId||sent.body.identity.campaign_id!==pending.campaign_id||sent.body.identity.invocation_id!==pending.invocation_id||sent.body.identity.item_id!==pending.protocol_binding.item_id||sent.body.identity.action_digest!==pending.protocol_binding.approved_action_sha256)throw Error('decision tuple crossed');}console.log('attention-deep-link-ok '+scenario+' '+attentionId)},50);
