const fs=require('fs'),vm=require('vm');
class CL{constructor(){this.s=new Set()}add(x){this.s.add(x)}remove(x){this.s.delete(x)}contains(x){return this.s.has(x)}toggle(x,f){if(f===undefined)f=!this.s.has(x);f?this.s.add(x):this.s.delete(x)}}
class E{constructor(tag='div'){this.tagName=tag;this.children=[];this.listeners={};this.dataset={};this.classList=new CL();this.textContent='';this.value='';this.disabled=false;this.files=[]}addEventListener(n,f){this.listeners[n]=f}append(...x){this.children.push(...x)}removeChild(x){this.children.splice(this.children.indexOf(x),1)}get firstChild(){return this.children[0]||null}closest(){return null}focus(){}scrollIntoView(){this.scrolled=true}setAttribute(n,v){this[n]=v}querySelector(){return null}click(){if(this._click)this._click()}}
const selectors=['#messages','#composer','#message','#send','#attachments','#attachment-tray','#status','#auth','#auth-form','#token','#connect','#auth-error','#developer-content','#developer-build','#detail-panel','#detail-content','#sound-settings','#presence-settings','#library-content','#library-search-form','#library-query','#history-content','#history-search-form','#history-query','#history-domain','.app-nav','#developer-sections','#detail-close','#chat-view','#developer-view','#settings-view','#library-view','#history-view'];
const n=Object.fromEntries(selectors.map(x=>[x,new E()]));n['#developer-build'].textContent='Build: test-build';
const devButton=new E('button');devButton.dataset.view='developer';devButton._click=()=>n['.app-nav'].listeners.click({target:{closest:()=>devButton}});
const attentionTab=new E('button');attentionTab.dataset.section='attention';
global.window={location:{origin:'http://localhost:8787',search:'?view=developer&section=attention&attention=attention-test'},localStorage:{getItem:()=> 'token',setItem(){}},setTimeout:(f)=>{f();return 1},clearTimeout(){},dispatchEvent(){}};
global.CustomEvent=class{};global.Event=class{};
global.document={querySelector(s){if(s==='.app-nav [data-view="developer"]')return devButton;return n[s]||null},querySelectorAll(s){if(s==='#developer-sections [data-section]')return [attentionTab];if(s==='.app-nav [data-view]')return [devButton];return []},getElementById(id){return descendants(n['#developer-content']).find(x=>x.id===id)||null},createElement:t=>new E(t),createElementNS:(_,t)=>new E(t),addEventListener(){}};
function descendants(x){return x.children.reduce((a,c)=>a.concat(c,descendants(c)),[])}
const scenario=process.env.FAWKES_ATTENTION_SCENARIO||'valid';
const pending={attention_id:'attention-test',campaign_id:'campaign-test',invocation_id:'invocation-test',state:scenario==='resolved'?'deny':'needs_tanner',blocked_action:'run harmless check',why_required:'protected boundary',requested_authority:'one harmless action',resources:['probe'],reversible:true};
global.fetch=async path=>{let status=200,data={};path=String(path);if(scenario==='auth'&&path!=='/api/status'){status=401;data={error:{message:'Access token required.'}}}else if(path==='/api/chat')data={phoenix:{name:'Fawkes'},conversation:{conversation_id:'c'},messages:[]};else if(path==='/api/status')data={build:{release_id:'test-build'}};else if(path==='/api/development/dashboard')data={};else if(path==='/api/development/codex-campaigns')data={campaigns:[]};else if(path==='/api/development/attention')data={attention:[pending]};else if(path.includes('/api/development/attention/attention-test')&&scenario==='unknown'){status=404;data={error:{message:'That Tanner attention request does not exist in this Fawkes build.'}}}else if(path.includes('/api/development/attention/attention-test'))data={attention:pending};else{status=404;data={error:{message:'Not found.'}}}return{status,ok:status<400,json:async()=>data}};
vm.runInThisContext(fs.readFileSync('src/app/static/app.js','utf8'),{filename:'app.js'});
setTimeout(()=>{const all=descendants(n['#developer-content']);const text=all.map(x=>x.textContent).join('\n');let wanted=scenario==='valid'?['Tanner: Fawkes is paused and needs your decision','What Fawkes wants to do','Why Fawkes stopped','Why Tanner’s permission is required','What will change if approved','What will not change','Who or what is affected','Risk level','Reversibility','Permission duration','Continuing authority','Fawkes’s recommendation','Approve Once','Deny','Cancel','Technical details']:scenario==='resolved'?['already resolved','deny']:scenario==='unknown'?['Attention request unavailable','unknown or no longer retained']:['Attention request unavailable','Access token required'];for(const value of wanted)if(!text.includes(value))throw Error('missing '+value+' in '+text);if(scenario==='valid'&&!all.some(x=>x.tagName==='details'))throw Error('technical details are not collapsed');if(!attentionTab.classList.contains('active'))throw Error('Attention tab not selected');if(scenario==='auth'&&n['#auth'].classList.contains('hidden'))throw Error('authentication boundary not shown');console.log('attention-deep-link-ok '+scenario)},25);
